language: node_js
node_js:
 - node
before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
before_script:
 - npm i -g --silent @angular/cli
script:
 - npm run build:prod
before_deploy:
 - export PKG_VERSION=`node -p "require('./package.json').version"`
 - git tag "${PKG_VERSION}-$(date +'%Y-%m-%d')";
deploy:
  - provider: releases
    api_key:
        secure: DxLTZyU3gRFzb73Wn1Ae55FTAe8MM7xFomN/gaH5zqFoIqjWYXHhdCdH7NQcbBUxkTcCWcCpnJXzHgO8RrADWaFhPFNIDRnQH2MYXGSpYlE79TkoqJ5OgDbSWLyRmrXLzdOT4Ez9ovXWvBUhW0tvdvJFKN0AMwliMIeLnPd5D3+3b6xLGSsNr0ffl1SHPmlDymnR2tYTBqy8R6zLYe5embsesDxV2q9NdUt+5PtbgyobSOdUxIkLAVlFEGXhNu2n5Pvqfn8qyug81XOPPRrH1f+vR0oTFw9Kw/lfpRt4LjWbYQ3o5EC1NRwoSImp6bcBHEJz372FQvJXb5OskYIdyzZVgZqr1YXZXCsGjIS2FE3/1wbMBFI6Pu7v+bQ2fOQTMU+ann4M3G7rNd3tBiK+dBIo2MeiKd2R0HPaV+xNF8ohJ7qqQkU+foc1FQYjSmcHclLXw4EWdpG+LZwAvk5EukjeZMytqaIWdHAHRfLWtQtVZZTlVf20Je6HIXZfNRkvgAW9l+RjW9+iKDnwAsb5vwDwH650aczooiJ0u1PcuvEfkDAETd/gnwtOzJ9i6EgJdKt/lSydEE9r1N22UBzY8b2ZSX5p2dGtPQbb0HmpDA+corQ7IUbLfR5E7G3uduUZLmJkcLPJ2ixIVhofGsc+AaEL2Vo8Dzvl0ptnYcaRgPU=
    file: "/dist/ngx-chronology"
    skip_cleanup: true
    on:
        branch: master
        condition: 'git tag -l "${PKG_VERSION}-$(date +'%Y-%m-%d')"' != "${PKG_VERSION}-$(date +'%Y-%m-%d')"
notifications:
    email:
        on_success: never
        on_failure: change
